### ISSUE TITLE
CI Uses thoughts 

### ISSUE THREAD

**Issue by LironHazan** [LironHazan/nx-size-limit#7]
The check should run as a post build phase and should only run for affected builds so I wonder how to have the check running as a "post build" somehow

**Comment by LironHazan** [comment]
Another thought is if cannot use [this](https://github.com/andresz1/size-limit-action) gha for getting results for multiple projects with nx would develop a dedicated one

**Comment by LironHazan** [comment]
This section does the job but would be nice to see the report as a comment on the PR.

```yaml
      - run: npx nx affected --target=build --base=origin/main

      - run: |
         APPS=( $(ls -1d dist/packages/*/ | xargs -n 1 basename) )
         echo "APPS=$APPS" >> $GITHUB_ENV

        env:
           APPS: ${{ env.APPS }}
      - run: |
           for app in $APPS; do
             npx nx run $app:size-limit
           done
```
